# Generated by Django 3.0.5 on 2020-08-28 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_name', models.CharField(max_length=50)),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=20)),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=20)),
                ('constituency', models.ForeignKey(db_column='constituency', on_delete=django.db.models.deletion.CASCADE, to='subject.Constituency')),
                ('county', models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_party_name', models.CharField(max_length=50)),
                ('party_logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_station_name', models.CharField(max_length=20)),
                ('number_of_voters', models.CharField(max_length=6)),
                ('constituency', models.ForeignKey(db_column='constituency', on_delete=django.db.models.deletion.CASCADE, to='subject.Constituency')),
                ('county', models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='subject.Location')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county_name', models.CharField(max_length=20)),
                ('county', models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=20)),
                ('constituency', models.ForeignKey(db_column='constituency', on_delete=django.db.models.deletion.CASCADE, to='subject.Constituency')),
                ('county', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublocation_name', models.CharField(max_length=20)),
                ('constituency', models.ForeignKey(db_column='constituency', on_delete=django.db.models.deletion.CASCADE, to='subject.Constituency')),
                ('county', models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
                ('sub_county', models.ForeignKey(db_column='sub_county', on_delete=django.db.models.deletion.CASCADE, to='subject.SubCounty')),
                ('ward', models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.CASCADE, to='subject.Ward')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, verbose_name='gender')),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('residential_area', models.CharField(max_length=50)),
                ('reg_voter', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1, verbose_name='registered voter')),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('constituency', models.ForeignKey(db_column='constituency', on_delete=django.db.models.deletion.CASCADE, to='subject.Constituency')),
                ('county', models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='subject.Location')),
                ('political_party', models.ForeignKey(db_column='political_party', on_delete=django.db.models.deletion.CASCADE, to='subject.PoliticalParty')),
                ('polling_station', models.ForeignKey(db_column='polling_station', on_delete=django.db.models.deletion.CASCADE, to='subject.PollingStation')),
                ('sub_county', models.ForeignKey(db_column='sub_county', on_delete=django.db.models.deletion.CASCADE, to='subject.SubCounty')),
                ('sublocation', models.ForeignKey(db_column='sublocation', on_delete=django.db.models.deletion.CASCADE, to='subject.SubLocation')),
                ('ward', models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.CASCADE, to='subject.Ward')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='sub_county',
            field=models.ForeignKey(db_column='sub_county', on_delete=django.db.models.deletion.CASCADE, to='subject.SubCounty'),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='sublocation',
            field=models.ForeignKey(db_column='sublocation', on_delete=django.db.models.deletion.CASCADE, to='subject.SubLocation'),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='ward',
            field=models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.CASCADE, to='subject.Ward'),
        ),
        migrations.AddField(
            model_name='location',
            name='sub_county',
            field=models.ForeignKey(db_column='sub_county', on_delete=django.db.models.deletion.CASCADE, to='subject.SubCounty'),
        ),
        migrations.AddField(
            model_name='location',
            name='ward',
            field=models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.CASCADE, to='subject.Ward'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('vying_position', models.CharField(choices=[('GOV', 'GOVERNER'), ('SEN', 'SENATOR'), ('WR', 'WOMEN REP'), ('MP', 'MEMBER OF PARLIAMENT'), ('MCA', 'MEMBER OF COUNTY ASSEMBLY')], max_length=3, verbose_name='elective position')),
                ('constituency', models.ForeignKey(db_column='constituency', on_delete=django.db.models.deletion.CASCADE, to='subject.Constituency')),
                ('county', models.ForeignKey(db_column='county', on_delete=django.db.models.deletion.CASCADE, to='subject.County')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='subject.Location')),
                ('polling_station', models.ForeignKey(db_column='polling_station', on_delete=django.db.models.deletion.CASCADE, to='subject.PollingStation')),
                ('sub_county', models.ForeignKey(db_column='sub_county', on_delete=django.db.models.deletion.CASCADE, to='subject.SubCounty')),
                ('sublocation', models.ForeignKey(db_column='sublocation', on_delete=django.db.models.deletion.CASCADE, to='subject.SubLocation')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(db_column='ward', on_delete=django.db.models.deletion.CASCADE, to='subject.Ward')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
